### ISSUE TITLE
Free updates e-mail content

### ISSUE THREAD

**Issue by caioertai** [mwalsh2020/lsat-cracked#105]
- subject: "Invitation instructions"
- hello: "Hello %{email}"
- someone_invited_you: "Someone has invited you to %{url}, you can accept it through the link below."
- accept: "Accept invitation"
- accept_until: "This invitation will be due in %{due_date}."
- ignore: "If you don't want to accept the invitation, please ignore this email. Your account won't be created until you access the link above and set your password."

@mwalsh2020

**Comment by mwalsh2020** [comment]
Welcome to LSAT Cracked!

Click here to create your free account and access the best LSAT content anywhere. If you're interested in a private coaching package, please reach out to me: matt@lsatcracked.com. Good luck on your LSAT journey!

Best,
Matt
