### ISSUE TITLE
[3-5] Tie in intro quiz to the sign up process

### ISSUE THREAD

**Issue by caioertai** [mwalsh2020/lsat-cracked#170]
- [x] Suggest sign up after quiz (clearer call to action ask for email)
- [x] Validate sign up call to action with Sean
- [x] Add `intro:boolean` to `articles` table. (uniqueness on model)
- [x] Home page should pick intro article to display as intro quiz
- [x] NTH: check CMS to add the intro check box for articles. ** created new issue #188 for this step

**Comment by caioertai** [comment]
This is finished, no? @jamiesonreinhard

**Comment by jamiesonreinhard** [comment]
@caioertai yeah this one is done.
