### ISSUE TITLE
[1] Add meta tags

### ISSUE THREAD

**Issue by caioertai** [mwalsh2020/lsat-cracked#20]
Currently there no description or social media meta tags

**Comment by caioertai** [comment]
Hey, @mwalsh2020 , please have a look a this:
https://web.dev/meta-description/?utm_source=lighthouse&utm_medium=devtools

I need a relevant description for the meta tags.

As an example for the relevancy of those:

**Whatever you put on the head:**
![image](https://user-images.githubusercontent.com/1820441/90314897-d111d680-dedc-11ea-8919-9d49fe99e26c.png)

**Is what's mainly used by Google:**
![image](https://user-images.githubusercontent.com/1820441/90314902-d8d17b00-dedc-11ea-894a-8be52c3fccfd.png)

**Comment by caioertai** [comment]
Also, more on this, @mwalsh2020.

A title tag with a sub heading would be better, it's currently:
- LSAT Cracked

Something with more than 15 character, like:
- LSAT Cracked: Improve your blah and blah blah

**Comment by caioertai** [comment]
A few suggestions for keywords and sentences based on Google Trends for LSAT over the past 90 days:
![image](https://user-images.githubusercontent.com/1820441/90324705-ba4c9d80-df37-11ea-9805-1bef34bca1ae.png)
![image](https://user-images.githubusercontent.com/1820441/90324731-07307400-df38-11ea-8568-a6786b393944.png)

**Comment by mwalsh2020** [comment]
Learn the skills needed for LSAT mastery. World-class instruction presented in a custom, modular format.  Stop wasting time, and start learning the right way.
